version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: sbpp-postgres
    environment:
      POSTGRES_USER: bet
      POSTGRES_PASSWORD: betpassword
      POSTGRES_DB: bet_core
    ports:
      - "5433:5432"          # exp√µe 5432 do container na 5433 local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bet -d bet_core"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrate:
    image: migrate/migrate
    container_name: sbpp-migrate
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: [
      "sh", "-c",
      "migrate -path /migrations -database postgres://bet:betpassword@postgres:5432/bet_core?sslmode=disable up"
    ]
    volumes:
      - ./internal/infra/db/sql/pg/migrations:/migrations
    restart: on-failure

  redis:
    image: redis:7-alpine
    container_name: sbpp-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: sbpp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc localhost 2181 | grep imok || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: sbpp-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # listeners: interno no cluster + externo local
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 5s
      timeout: 10s
      retries: 20

  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: sbpp-prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./build/compose/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - kafka
      - postgres
      - redis

  grafana:
    image: grafana/grafana:11.1.0
    container_name: sbpp-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
    volumes:
      - ./build/compose/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./build/compose/grafana/dashboards:/var/lib/grafana/dashboards:ro

volumes:
  postgres_data:
  redis_data:
